### ISSUE TITLE
Can this backward compatible version

### ISSUE THREAD

**Issue by new123-ui** [sqids/sqids-php#10]

**Comment by 4kimov** [comment]
Hi @new123-ui, ticket is not clear. Please re-open with more info.

**Comment by new123-ui** [comment]
This tool can only be compatible php8 above version，Is it compatible with php7.4

**Comment by new123-ui** [comment]
My English is a little poor, please forgive me

**Comment by 4kimov** [comment]
@new123-ui No problem, thanks for elaborating.

No, unfortunately, official support is for 8.1 and higher. See here: https://github.com/sqids/sqids-php/issues/7

**Comment by new123-ui** [comment]
Thank you for your reply. It is a pity that there is no other version

**Comment by vinkla** [comment]
I recommend upgrading to the latest PHP version as versions below 8.1 no longer receive security updates.

[![php versions](https://github.com/sqids/sqids-php/assets/499192/ccd92ae5-76e2-4f92-a336-c2054e4aee25)](https://www.php.net/supported-versions.php)

**Comment by new123-ui** [comment]
OK, Thank you for your reply
