### ISSUE TITLE
best practices for implementation shuffle length and id length?

### ISSUE THREAD

**Issue by slushpuppy** [sqids/sqids-php#13]
Hello, 

 I would like to seek advice on implementation based on some of the caveats mentioned in documentation where identical hash outputs are the same:

- Should id lengths beyond a certain size be split into arrays? 
- Is there a relation between shuffle length and max id length support?

Thanks for replying

**Comment by 4kimov** [comment]
Sorry, I'm not sure I follow the questions.

> Should id lengths beyond a certain size be split into arrays?

IDs are just strings, what do you mean by arrays and what's your goal?

> Is there a relation between shuffle length and max id length support?

There is no max ID length support. There's only a padding feature controlled via `minLength`
