### ISSUE TITLE
Encoded value can have characters behind it when decoding

### ISSUE THREAD

**Issue by ronaldgj** [sqids/sqids-php#14]
Hi there!

First of all, great features! Love it.

I came across the following. When I encode a database id, for example 1, I get an encoded value back. I've set my own alphabet and a pad of 8.

Now when I want to decode it I saw that I can place as many characters behind it as I want.

**Example**
ID: 1
SQID: 9fl48ghy

When I decode `9fl48ghy`, I get `[1]`.
But when I decode `9fl48ghyjf0293jf09sjd0f9j209fj`, I get also [1].

Also when I change the last character it still passes? 😱  (`9fl48ghy` --> `9fl48gha`)

Is this normal behavior or is it a bug?

**Comment by 4kimov** [comment]
Normal behavior, that's how padding works - adds junk characters at the end.

https://sqids.org/faq#valid-ids

**Comment by ronaldgj** [comment]
> Normal behavior, that's how padding works - adds junk characters at the end.
> 
> https://sqids.org/faq#valid-ids

Ah, the FAQ makes it clear! I'll make an extra check with encoding back and check if they match.
