### ISSUE TITLE
Publishing v0.1.0

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-php#3]
@vinkla The main lib & tests are there, there's not much extra to add from the spec. Anything else would be PHP-specific. A few questions for you before we publish v0.1.0:

1. Is there a good way to export `DEFAULT_BLOCKLIST` so it can be used outside of the package like the other 2 default constants?
2. The encoding/decoding tests are passing (which means they're producing the right IDs), but I'm not sure what the upper limit for PHP ints would be. Is bcmath/gmp usage correct along with max upper bound?
3. Same for `mb_` functions. The spec does not promise Unicode support ([too many issues](https://github.com/orgs/sqids/discussions/1)). Anything to adjust in this lib regarding that? Is it even worth having `mb_` functions?

**Comment by miquelfire** [comment]
I'll answer some things I know about

2. Max upper bound is interesting. If you're using BCMath or GMP, technically there is no upper bound. The upper bound would depend on the system the script runs on. Both libraries support passing numbers in strings to bypass the PHP_MAX_INT limit. For the best performance, PHP_MAX_INT with GMP minus a few for whatever buffer the algorithm would need (I haven't looked at the algorithm for sqids yet) as that would have GMP run with the native CPU adders, but the moment a calculation goes above it, it uses some complex code that is meant to scale REALLY large. You could pass a 2048-bit number in a string, and it would run just fine.

The other two I haven't made a PHP library, so I'll leave that up to someone else (I'm in a smaller boat than you)

**Comment by 4kimov** [comment]
I'll publish the package as `v0.1.0` to move things a bit forward & update the site. Since the generated IDs are whats expected, any changes should be backwards-compatible (to the spec) **except for** possibly function definitions (since @miquelfire mentioned ints as strings is possible; right now it accepts/returns only ints).

**Comment by vinkla** [comment]
1. It is possible to store the complete array as a constant within the class instead of using JSON.

2. @4kimov, is there any information in the specification regarding the utilization of dependencies? I am considering the option of importing the math functions through a library.

3. As far as I am aware, PHP inherently supports utf-8, and we might be able to omit the usage of `mb_` functions. If this becomes a concern in the future, we can always incorporate it later.

**Comment by 4kimov** [comment]
1. Ah ok, good. I'm assuming somehow through a separate file so it doesn't make the main one difficult to manage?
2. Some languages rely on dependencies so we removed the "no dependencies" description on the website. Basically, if it's reasonable - then no problem.
3. Ok, I agree.

**Comment by vinkla** [comment]
1. If it's a class constant, we cannot store it in another file. However, we can create a static method to retrieve the list, although it may not be as convenient as a constant. [I've submitted a pull request.](https://github.com/sqids/sqids-php/pull/5) Please review and share your thoughts.

**Comment by 4kimov** [comment]
Hm, I see. I'm not sure I'm the biggest fan of this approach regarding constants just because it makes the library harder to work with (since it's a bigger file), and future updates to the blocklist will be more "public" so to say (currently `.gitattributes` keeps changes more hidden for that json file; the user doesn't *really* need to know which new inappropriate words will be added in the future).

However, I'm no expert in PHP, so if you think that's the best way to go about it, then let's do that. After all, the goal is to make it easier for the end user to merge the default blocklist with their own custom words.

**Comment by vinkla** [comment]
I agree that it's not the best solution, but I'm unaware of any alternative methods to achieve this.

**Comment by 4kimov** [comment]
Is a public static `get_default_blocklist()` too ugly or not idiomatic? Or would it be cleaner to have `DEFAULT_BLOCKLIST`?

**Comment by vinkla** [comment]
Personally, I would say it would be cleaner with the constant.

**Comment by 4kimov** [comment]
@vinkla Ok cool, merged your PR 🙏 

Also removed `mb_` functions. Since this is pre-production version, I'm going to tag it as `0.2.0` a bit later, unless you or @miquelfire can think of anything else to adjust.

Closing for now. Thank you both.
