### ISSUE TITLE
Downgrade to PHP 8.1?

### ISSUE THREAD

**Issue by roukmoute** [sqids/sqids-php#4]
The php version would have to be downgraded to php 8.1, which is still active until Nov 25, 2023, and would prevent Symfony, for example, from working by default (via config.platform).

**Comment by 4kimov** [comment]
I might need some help on PHP version related issues. @vinkla @miquelfire any thoughts on this?

**Comment by miquelfire** [comment]
One thing to note: PHP versions are actually supported for [3 years](https://www.php.net/supported-versions.php), 2 years of active support, and then another year for security updates (a new version of PHP 8.0 actually just released today)

As it might take us a while to make our first release, I don't see a reason to not drop it down to 8.1, just need to make sure the tests don't fail with that version.

**Comment by 4kimov** [comment]
@miquelfire Cool, thanks for more info. I just noticed [this commit](https://github.com/sqids/sqids-php/commit/94653ac2dfb40aebe153fadd0652d8b4f89f56d1) by @vinkla, so I'm guessing there was a reason for it. Gonna wait for him to take a look.

**Comment by vinkla** [comment]
Since this is a new package, I suggest targeting the latest version of PHP. As package maintainers, I think we should encourage developers to use updated PHP versions. By doing so, we can take advantage of the latest PHP features without the immediate need for backward compatibility. As mentioned by @roukmoute, PHP will end active support for PHP 8.1 later this year. If we skip that version, we will have one less version to worry about. It's also worth mentioning that both Laravel and Symfony will end support for PHP 8.1 this year.

**Comment by 4kimov** [comment]
@roukmoute, @vinkla's explanation makes sense to me. Do you have a blocker that's preventing you or is this just to have wider support?

**Comment by roukmoute** [comment]
I understand your reasons for opting for the latest version of PHP for this new package. However, let me share a different perspective.

It's true that a new library might naturally tend towards using the most recent version. However, it's essential to recognize that many projects aren't necessarily up to date with the latest versions. From this point of view, it could be beneficial to make our library compatible with slightly earlier versions, such as PHP 8.1, to encourage its adoption by a greater number of users.

The idea of encouraging developers to use the latest versions is a noble one. However, imposing an update could be perceived not as an incentive, but as a constraint. If the aim is to encourage, perhaps we should consider providing support for PHP 8.1 while highlighting the benefits of transitioning to newer versions?

Of course, I respect the direction you wish to take the project. This reflection is simply an invitation to consider all perspectives.

**Comment by vinkla** [comment]
Thank you for sharing your opinion. I believe you are making a valid point in supporting PHP 8.1 to encourage adoption. At the same time, upgrading from PHP 8.1 to 8.2 is not that difficult. Frameworks like Laravel and Symfony already support 8.2, so it's essentially just a matter of switching versions. It's also worth considering that by the time we reach version 1.0 of this library, PHP 8.3 might have already been released. This is not set in stone, so let's reconsider this if there is a broader request for supporting older PHP versions.

**Comment by vinkla** [comment]
PHP 8.1 support added in #8.
